### ISSUE TITLE
Docker compatibility issues with Drake

### ISSUE THREAD

**Issue by rishifactual** [Factual/drake#196] opened 2015-08-20 18:10 UTC
CC @bfs in case this is strictly a Docker config issue.

Using the [latest version of docker-cdh5-dev container](https://github.com/bfs/docker-cdh5-dev/blob/227eed6a67e3a897cccfb3c09e3dbc2006746aa0/Dockerfile), which now has [drake installation steps](https://github.com/bfs/docker-cdh5-dev/blob/227eed6a67e3a897cccfb3c09e3dbc2006746aa0/Dockerfile#L15-L17), I am able to invoke drake and run menu commands like `$ drake --help` and `$ drake --version`. However, when I try and run a simple drake workflow/step, I'm getting various Java exceptions.

For example, if I invoke the following drakefile
```
;test.d

%fakestep <- 
   echo Hello World
```
using command `$ drake -w test.d +%fakestep` from inside my docker container, I am getting the following Java ClassCastException:

```bash
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
	at drake.shell$shell.doInvoke(shell.clj:96)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at drake.protocol$run_interpreter.invoke(protocol.clj:86)
	at drake.protocol_interpreters$register_interpreter_BANG_$reify__4637.run(protocol_interpreters.clj:13)
	at drake.core$run_step.invoke(core.clj:367)
	at drake.core$attempt_run_step.invoke(core.clj:479)
	at drake.core$function_for_step$fn__5045.invoke(core.clj:502)
	at drake.core$trigger_futures_helper$fn__5056.invoke(core.clj:540)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I am not sure if this is an issue with the docker container not having all the correct dependencies installed, or if this is something on drake's end. Or if I'm doing something stupid and haven't realized it.

**Comment by rishifactual** [comment] 2015-08-20 18:12
Some more information about the issue:

drake version = 1.0.1

How to recreate the error:
1. install docker
2. pull the docker image with `sudo docker pull factual/docker-cdh5-dev`
3. launch bash within the container with `sudo docker run -i -t factual/docker-cdh5-dev /bin/bash`
4. create a simple drakefile and run drake as you normally would

**Comment by rishifactual** [comment] 2015-08-20 18:21
Just to update:

```
;test.d

%fakestep <- [ruby[
   puts 'Hello World'
```

will execute properly and print 'Hello World' to STDOUT. So presumably it's something wrong with bash?

**Comment by amalloy** [comment] 2015-08-20 18:23
Actually `[ruby[`, not `[ruby]`?

**Comment by rishifactual** [comment] 2015-08-20 18:25
Typo, I edited my post. Sorry about that.

**Comment by amalloy** [comment] 2015-08-20 18:29
Anyway, that exception looks to me like it might happen if your `SHELL` environment variable were unset. If you want to use bash, verify that it's set to `/bin/bash`. Does that help?

**Comment by rishifactual** [comment] 2015-08-20 18:55
SHELL is set to /bin/bash already.

**Comment by amalloy** [comment] 2015-08-20 19:05
Sorry to sound skeptical, but...are you sure? This is the exact error you get if `SHELL` is unset, and after looking through the step-running code I can't think of any other circumstance that would case this stacktrace. Here's what happens to me when I unset `SHELL` and run drake myself locally:

```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
	at drake.shell$shell.doInvoke(shell.clj:96)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at drake.protocol$run_interpreter.invoke(protocol.clj:86)
	at drake.protocol_interpreters$register_interpreter_BANG_$reify__4639.run(protocol_interpreters.clj:13)
	at drake.core$run_step.invoke(core.clj:367)
	at drake.core$attempt_run_step.invoke(core.clj:479)
	at drake.core$function_for_step$fn__5047.invoke(core.clj:502)
	at drake.core$trigger_futures_helper$fn__5058.invoke(core.clj:540)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rishifactual** [comment] 2015-08-20 19:07
positive

**Comment by amalloy** [comment] 2015-08-20 19:08
And I have docker installed but can't pull this image to reproduce: 

```
$ docker pull factual/docker-cdh5-dev
Using default tag: latest
Pulling repository docker.io/factual/docker-cdh5-dev
Network timed out while trying to connect to https://index.docker.io/v1/repositories/factual/docker-cdh5-dev/images. You may want to check your internet connection or if you are behind a proxy.
```

**Comment by stfactual** [comment] 2015-08-20 19:10
By the way, POSIX's system() function is specified to use /bin/sh as a
fallback; I think adding that as an alternative to the (get) at
https://github.com/Factual/drake/blob/develop/src/drake/shell.clj#L93 would
be a reasonable thing to do (and would make the error message a little more
obvious, e.g. if the user has no /bin/sh).

On Thu, Aug 20, 2015 at 12:08 PM, Alan Malloy <notifications@github.com>
wrote:

> And I have docker installed but can't pull this image to reproduce:
>
> $ docker pull factual/docker-cdh5-dev
> Using default tag: latest
> Pulling repository docker.io/factual/docker-cdh5-dev
> Network timed out while trying to connect to https://index.docker.io/v1/repositories/factual/docker-cdh5-dev/images. You may want to check your internet connection or if you are behind a proxy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Factual/drake/issues/196#issuecomment-133124842>.
>



-- 

*Factual Confidential Information*
Any non-public information in this email is Factual's confidential
information.  It is only for use by the intended recipient under the terms
of a non-disclosure agreement or other binding confidentiality terms.  If
you've gotten this email in error, please let the sender know of the
mistake and delete the email immediately.

**Comment by yoshimotob** [comment] 2015-08-20 19:11
Btw, I ran into this same error:
https://github.com/Factual/drake/issues/171
I fixed by adding:
export SHELL="/bin/bash"
, as mentioned.  Make sure it's in the script that runs on the docker to initialize things.  You can't rely on the launch environment to pass it through.

**Comment by rishifactual** [comment] 2015-08-20 19:14
Jeez,that's bizarre, it works when I explicitly `$ export SHELL=/bin/bash`...but prior to that, SHELL was already set to /bin/bash?!?!

**Comment by amalloy** [comment] 2015-08-20 19:14
Set but not exported, perhaps.

**Comment by rishifactual** [comment] 2015-08-20 19:15
Seems like it. Weird.

Thanks guys. My "echo hello world" drake workflow is working now, let me just make sure I'm not having any other issues before shutting this ticket down.

**Closed by amalloy** 2015-08-20 19:14 UTC

**Comment by amalloy** [comment] 2015-08-20 19:50
FWIW at @stfactual's suggestion I wrote 94b3d27, which defaults to using /bin/sh and issues a warning, if SHELL isn't set.

**Comment by dirtyvagabond** [comment] 2015-08-20 21:04
@amalloy does your change prevent the arcane `ClassCastException`, or is that still a possibility?

**Comment by amalloy** [comment] 2015-08-20 21:17
It should be 100% impossible now. The issue was that into-array was being called on a seq: into-array infers the array's type from the seq's first element, and not having SHELL set caused the first argument to be nil rather than a string, so we got Object[] instead of String[]. I've made two changes, each of which alone should be enough to prevent that:

- Specify the expected String[] type explicitly
- Make sure the first element is never nil, by using a default value for SHELL

**Comment by dirtyvagabond** [comment] 2015-08-20 22:00
:+1:
